name: baoffres-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: retrieve code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker-compose build

      - name: Launch test & build
        env:
          DB_NAME: ${{ secrets.DB_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          REDIS: ${{ secrets.REDIS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

        run: docker-compose run api python manage.py test

      - name: Clean docker environment
        run: docker-compose down
